image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - aaron-bond.better-comments@2.1.0:w1dHZXyFPGn7vpca57Nf5g==
    - CoenraadS.bracket-pair-colorizer-2@0.1.4:+JUeb/jFYZt2/0MS/gUllA==
    - esbenp.prettier-vscode@5.5.0:xcEnHt0vYXkhJ8IkBmNAuA==
    - PKief.material-icon-theme@4.2.0:BMxWnfsRyjgBONLuFiMF4g==
    - HookyQR.beautify@1.4.11:n9DJEUFbYD/YHaBXxm+pYw==
    - christian-kohler.path-intellisense@2.2.1:fMWBG5pfnZrunkTMwUwEDg==
    - James-Yu.latex-workshop@8.11.1:FJO7gUiiukqrFr3H15q9kQ==
    - donjayamanne.githistory@0.6.9:ZuSpHC+Smmz7WQRRorLS0A==
    - vscode-icons-team.vscode-icons@10.2.0:DrQUJPtFm0woSFiyitha8Q==